"""End-to-end integration tests for the full specprobe pipeline (T020).

Validates Unix pipeline composition:
  specprobe search --source-title "Petstore Probe API" --full
  | specprobe generate | specprobe export
Verifying that unranked filter search results pass seamlessly through local test generation
and deterministic artifact export to produce runnable Postman and REST Client files.
"""

import json
import re
import shutil
from pathlib import Path
from unittest.mock import MagicMock, patch

from click.testing import CliRunner

from specprobe.cli import cli


def _mock_completion(content: str) -> MagicMock:
    """Helper to generate a mock LiteLLM completion response object."""
    mock_resp = MagicMock()
    mock_choice = MagicMock()
    mock_choice.message.content = content
    mock_resp.choices = [mock_choice]
    return mock_resp


def _index_fixture(runner: CliRunner, fixture_path: str, index_dir: str) -> None:
    """Helper to decompose and index an OpenAPI specification into a target directory."""
    chunk_res = runner.invoke(cli, ["chunk", fixture_path])
    assert chunk_res.exit_code == 0
    index_res = runner.invoke(cli, ["index", "--index-dir", index_dir], input=chunk_res.output)
    assert index_res.exit_code == 0


def test_full_pipeline_search_generate_export(tmp_path: Path) -> None:
    """Verify full pipeline: search --full | generate | export --format both --output <dir>."""
    runner = CliRunner()
    index_dir = str(tmp_path / "index")
    export_dir = tmp_path / "exported_pipeline"
    cache_dir = tmp_path / "cache"

    # Step 1: Populate local search index with Petstore OpenAPI spec
    _index_fixture(runner, "tests/fixtures/valid_openapi_30.yaml", index_dir)

    # Step 2: Extract unranked search results with full chunk payloads
    search_res = runner.invoke(
        cli,
        [
            "search",
            "--source-title",
            "Petstore Probe API",
            "--full",
            "--index-dir",
            index_dir,
        ],
    )
    assert search_res.exit_code == 0
    search_json = search_res.output
    assert len(json.loads(search_json)) == 4

    # Step 3: Mock LLM completions and pipe search output into generate
    shutil.copytree("tests/fixtures/cache", cache_dir)

    def _mock_dispatch(*args, **kwargs):
        messages = kwargs.get("messages", [])
        op_id = "mockOp"
        for m in messages:
            content = m.get("content", "")
            match = re.search(r"Operation ID:\s*([^\s\n\r]+)", content, re.IGNORECASE)
            if match:
                op_id = match.group(1).strip()
                break
        return _mock_completion(
            json.dumps(
                {
                    "operation_id": op_id,
                    "description": f"Integration test scenario for {op_id}",
                    "request": {
                        "path_params": {"petId": "123"},
                        "query_params": {"limit": 10},
                        "headers": {"Accept": "application/json"},
                        "body": {"name": "TestPet"} if "create" in op_id.lower() else None,
                    },
                    "response": {
                        "status_code": 201 if "create" in op_id.lower() else 200,
                        "headers": {"Content-Type": "application/json"},
                        "schema_shape": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "integer"},
                                "name": {"type": "string"},
                            },
                        },
                    },
                    "tags": ["pets"],
                }
            )
        )

    with patch("litellm.completion", side_effect=_mock_dispatch):
        gen_res = runner.invoke(
            cli,
            ["generate", "-", "--cache-dir", str(cache_dir)],
            input=search_json,
        )

    assert gen_res.exit_code == 0
    generated_jsonl = gen_res.output
    lines = [line.strip() for line in generated_jsonl.strip().splitlines() if line.strip()]
    assert len(lines) == 4

    # Step 4: Pipe generated test cases JSONL into export
    export_res = runner.invoke(
        cli,
        [
            "export",
            "-",
            "--format",
            "both",
            "-o",
            str(export_dir),
            "--collection-name",
            "Pipeline Export Collection",
            "--base-url",
            "http://127.0.0.1:8000",
        ],
        input=generated_jsonl,
    )

    assert export_res.exit_code == 0

    col_file = export_dir / "collection.json"
    http_file = export_dir / "requests.http"

    assert col_file.exists(), "collection.json was not generated by pipeline"
    assert http_file.exists(), "requests.http was not generated by pipeline"

    # Verify Postman collection parses and contains all operations
    col_data = json.loads(col_file.read_text(encoding="utf-8"))
    assert col_data["info"]["name"] == "Pipeline Export Collection"
    assert col_data["variable"][0]["value"] == "http://127.0.0.1:8000"
    # Tag folder "pets" should contain the 4 generated items
    assert len(col_data["item"]) == 1
    assert col_data["item"][0]["name"] == "pets"
    assert len(col_data["item"][0]["item"]) == 4

    # Verify REST Client document parses and contains requests
    http_doc = http_file.read_text(encoding="utf-8")
    assert http_doc.startswith("@baseUrl = http://127.0.0.1:8000\n")
    assert "@apiKeyAuth = <api_key>" in http_doc
    assert http_doc.count("###") == 4
    assert "# @name listPets" in http_doc
    assert "# @name createPets" in http_doc
    assert "# @name showPetById" in http_doc
    assert "# @name delete_pets_pet_id" in http_doc
    assert "Exported 4 test cases to" in export_res.stderr
